class Subject

  DATA = [
    "Action & Adventure",
    "African American",
    "Art & Architecture",
    "Arts & Entertainment",
    "Astronomy",
    "Biography",
    "Biography & Memoir",
    "Business",
    "Business & Personal Finance",
    "Careers",
    "Chemistry",
    "Children & Teens",
    "Classics",
    "Comedy",
    "Computers & Internet",
    "Contemporary",
    "Cooking",
    "Cookbooks, Food & Wine",
    "Current Events",
    "Design",
    "Earth Sciences",
    "Economics",
    "Education",
    "Engineering",
    "Erotica",
    "Family & Relationship",
    "Fantasy",
    "Fiction",
    "Fiction & Literature",
    "Finance",
    "Food & Wine",
    "Games",
    "Gay",
    "Ghost",
    "Health",
    "Health, Mind & Body",
    "History",
    "Humor",
    "Industries & Professions",
    "Investing",
    "Law",
    "Life Sciences",
    "Lifestyle",
    "Lifestyle & Home",
    "Literature",
    "Literary Criticism",
    "Management",
    "Management & Leadership",
    "Marketing",
    "Marketing & Sales",
    "Mathematics",
    "Medical",
    "Music",
    "Mysteries",
    "Mysteries & Thrillers",
    "Nature",
    "Nonfiction",
    "Parenting",
    "Performing Arts",
    "Personal Finance",
    "Philosophy",
    "Photography",
    "Physics",
    "Poetry",
    "Politics",
    "Politics & Current Events",
    "Professional & Technical",
    "Psychology",
    "Reference",
    "Religious",
    "Romance",
    "Sci-Fi & Fantasy",
    "Science",
    "Science & Nature",
    "Science Fiction",
    "Self-Improvement",
    "Short Stories",
    "Small Business & Entrepreneurship",
    "Social Science",
    "Spirituality",
    "Sports",
    "Sports & Outdoors",
    "Suspense",
    "Technology",
    "Theater",
    "Transportation",
    "Travel",
    "Travel & Adventure",
    "Western",
    "Young Adult"
  ]

  def self.subjects
    @subjects ||= DATA.sort
  end

  def self.closestMatch(string)
    subjects.find {|name| name.match(/^#{string}/i)}
  end

end
